---
id: identity-profile-identity-error-report-arguments
title: IdentityProfileIdentityErrorReportArguments
pagination_label: IdentityProfileIdentityErrorReportArguments
sidebar_label: IdentityProfileIdentityErrorReportArguments
sidebar_class_name: pythonsdk
keywords: ['python', 'Python', 'sdk', 'IdentityProfileIdentityErrorReportArguments', 'IdentityProfileIdentityErrorReportArguments'] 
slug: /tools/sdk/python/v3/models/identity-profile-identity-error-report-arguments
tags: ['SDK', 'Software Development Kit', 'IdentityProfileIdentityErrorReportArguments', 'IdentityProfileIdentityErrorReportArguments']
---

# IdentityProfileIdentityErrorReportArguments

Arguments for Identity Profile Identity Error report (IDENTITY_PROFILE_IDENTITY_ERROR)

## Properties

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**authoritative_source** | **str** | Source ID. | [required]
}

## Example

```python
from sailpoint.v3.models.identity_profile_identity_error_report_arguments import IdentityProfileIdentityErrorReportArguments

identity_profile_identity_error_report_arguments = IdentityProfileIdentityErrorReportArguments(
authoritative_source='1234sourceId5678902'
)

```
[[Back to top]](#) 

